### PR TITLE
Include DeleteList and UpdateList operations

### PR DESCRIPTION
**Pull request by maikmb**
- Implement DeleteList usecase and graphQL mutation
- Implement UpdateList graphQL mutation and test class

### CODE REVIEW

**Comment by jhomarolo-vortx** [comment]
Olá Maik, tudo bem? 
Consegue abrir uma issue e associar este PR lá?

**Comment by maikmb** [comment]
@jhomarolo-vortx , segue issue:

 https://github.com/herbsjs/todolist-on-herbs/issues/5

**Comment by maikmb** [comment]
Acho que eu não tenho acesso para relacionar com a issuer.

**Comment by jhomarolo-vortx** [comment]
I believe that the documentation update is missing to describe how to use

**Comment by maikmb** [comment]
Yes! I will update it soon and return for validation.

**Comment by jhomarolo-vortx** [comment]
Great! I'll wait for you

**Comment by jhomarolo-vortx** [comment]
Hi @maikmb we made some structural changes to your project and your pull request broke, can you adjust it again so we can approve it?

**Comment by maikmb** [comment]
Hi @ jhomarolo-vortx! 
I updated the source branch, but some checks were unsuccessful. It appears that the code coverage is less than 80%! How can we increse code coverage? With more tests?

**Comment by dalssoft** [comment]
please, push from master to remove node_modules from this PR

**Comment by jhomarolo** [comment]
Hi @maikmb, you can see your test coverage locally to see where you can improve.

Also, please remove node_modules from your commit to evaluate PR

**Comment by maikvortx** [comment]
@dalssoft and @jhomarolo , i will improve the test coverage. About **node_modules**, i think that, i can add .gitignore with this path.

**Comment by jhomarolo** [comment]
Hi @maikmb great, I'll wait for the update

**Comment by maikvortx** [comment]
Hi @jhomarolo! I removed ** node_modules ** from the root project. I didn't add **. gitignore **, because the file already exists in the ** backend ** and ** frontend ** directories. 

I will improve the test coverage and return with this PR!

**Comment by jhomarolo** [comment]
Okay @maikmb thanks for quickly response.  I'll wait for the update

**Comment by dalssoft** [comment]
any update on this PR?

**Comment by maikmb** [comment]
@jhomarolo-vortx 
@dalssoft 

You can approve this PR?

**Comment by jhomarolo** [comment]
Hello @maikmb , I will approve this PR to proceed with this demand.

However your PR has reduced testing coverage and I would very much like to see a new PR with increased coverage again.

Thank you

**Comment by maikmb** [comment]
Hi @jhomarolo !
I will increase test coverage in another PR!
Thanks!

**Pull request merged**
